package graph

// This file will be automatically regenerated based on the schema, any resolver
// implementations
// will be copied through when generating and any unknown code will be moved to the end.
// Code generated by github.com/99designs/gqlgen version v0.17.93

import (
	"context"
	"time"
	"wardrobe-graphql/graph/generated"
	"wardrobe-graphql/graph/model"
)

// Dictionaries is the resolver for the dictionaries field.
func (r *queryResolver) Dictionaries(ctx context.Context) ([]*model.Dictionary, error) {
	// Service : Find all dictionary
	data, err := r.DictionaryService.FindAllDictionaries()

	if err != nil {
		return nil, err
	}

	result := make([]*model.Dictionary, 0)
	for _, d := range data {
		result = append(result, &model.Dictionary{
			ID:             d.ID.String(),
			DictionaryType: d.DictionaryType,
			DictionaryName: d.DictionaryName,
			CreatedAt:      d.CreatedAt.Format(time.RFC3339),
		})
	}

	return result, nil
}

// Query returns generated.QueryResolver implementation.
func (r *Resolver) Query() generated.QueryResolver { return &queryResolver{r} }

type queryResolver struct{ *Resolver }
