package graph

// This file will be automatically regenerated based on the schema, any resolver
// implementations
// will be copied through when generating and any unknown code will be moved to the end.
// Code generated by github.com/99designs/gqlgen version v0.17.93

import (
	"context"
	"time"
	"wardrobe-graphql/graph/generated"
	"wardrobe-graphql/graph/model"
	"wardrobe-graphql/models"
)

// CreateDictionary is the resolver for the createDictionary field.
func (r *mutationResolver) CreateDictionary(ctx context.Context, input model.CreateDictionaryInput) (*model.Dictionary, error) {
	// Service : Create dictionary
	dictionary, err := r.DictionaryService.CreateDictionary(
		input.DictionaryType,
		input.DictionaryName,
	)

	if err != nil {
		return nil, err
	}

	return &model.Dictionary{
		ID:             dictionary.ID.String(),
		DictionaryType: dictionary.DictionaryType,
		DictionaryName: dictionary.DictionaryName,
		CreatedAt:      dictionary.CreatedAt.Format(time.RFC3339),
	}, nil
}

// CreateQuestion is the resolver for the createQuestion field.
func (r *mutationResolver) CreateQuestion(ctx context.Context, input model.CreateQuestionInput) (*model.Question, error) {
	question := &models.Question{
		Question: input.Question,
	}

	if err := r.QuestionService.CreateQuestion(question); err != nil {
		return nil, err
	}

	return &model.Question{
		ID:        question.ID.String(),
		Question:  question.Question,
		Answer:    question.Answer,
		IsShow:    question.IsShow,
		CreatedAt: question.CreatedAt.String(),
	}, nil
}

// DeleteDictionaryByID is the resolver for the deleteDictionaryById field.
func (r *mutationResolver) DeleteDictionaryByID(ctx context.Context, id string) (bool, error) {
	return r.DictionaryService.DeleteDictionaryById(id)
}

// DeleteFeedbackByID is the resolver for the deleteFeedbackById field.
func (r *mutationResolver) DeleteFeedbackByID(ctx context.Context, id string) (bool, error) {
	return r.FeedbackService.DeleteFeedbackById(id)
}

// DeleteQuestionByID is the resolver for the deleteQuestionById field.
func (r *mutationResolver) DeleteQuestionByID(ctx context.Context, id string) (bool, error) {
	return r.QuestionService.DeleteQuestionById(id)
}

// Dictionaries is the resolver for the dictionaries field.
func (r *queryResolver) Dictionaries(ctx context.Context) ([]*model.Dictionary, error) {
	// Service : Find all dictionary
	data, err := r.DictionaryService.FindAllDictionaries()

	if err != nil {
		return nil, err
	}

	result := make([]*model.Dictionary, 0)
	for _, d := range data {
		result = append(result, &model.Dictionary{
			ID:             d.ID.String(),
			DictionaryType: d.DictionaryType,
			DictionaryName: d.DictionaryName,
			CreatedAt:      d.CreatedAt.Format(time.RFC3339),
		})
	}

	return result, nil
}

// QuestionAnswered is the resolver for the questionAnswered field.
func (r *queryResolver) QuestionAnswered(ctx context.Context, limit *int) ([]*model.Question, error) {
	// Param Optional
	limitParam := 6
	if limit != nil {
		limitParam = *limit
	}

	// Service : Find random question answer
	data, err := r.QuestionService.FindRandomAnsweredQuestion(limitParam)

	if err != nil {
		return nil, err
	}

	result := make([]*model.Question, 0)
	for _, d := range data {
		result = append(result, &model.Question{
			ID:        d.ID.String(),
			Question:  d.Question,
			Answer:    d.Answer,
			IsShow:    d.IsShow,
			CreatedAt: d.CreatedAt.Format(time.RFC3339),
		})
	}

	return result, nil
}

// Mutation returns generated.MutationResolver implementation.
func (r *Resolver) Mutation() generated.MutationResolver { return &mutationResolver{r} }

// Query returns generated.QueryResolver implementation.
func (r *Resolver) Query() generated.QueryResolver { return &queryResolver{r} }

type (
	mutationResolver struct{ *Resolver }
	queryResolver    struct{ *Resolver }
)
